// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import v1alpha1 "hidevops.io/cube/pkg/apis/cube/v1alpha1"

// IngressService is an autogenerated mock type for the IngressService type
type IngressService struct {
	mock.Mock
}

// CreateIngress provides a mock function with given fields: gatewayConfig
func (_m *IngressService) CreateIngress(gatewayConfig *v1alpha1.GatewayConfig) error {
	ret := _m.Called(gatewayConfig)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.GatewayConfig) error); ok {
		r0 = rf(gatewayConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: name, namespace
func (_m *IngressService) Delete(name string, namespace string) error {
	ret := _m.Called(name, namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
