// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import v1alpha1 "hidevops.io/cube/pkg/apis/cube/v1alpha1"

// KongService is an autogenerated mock type for the KongService type
type KongService struct {
	mock.Mock
}

// CreateKong provides a mock function with given fields: gatewayConfig
func (_m *KongService) CreateKong(gatewayConfig *v1alpha1.GatewayConfig) error {
	ret := _m.Called(gatewayConfig)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.GatewayConfig) error); ok {
		r0 = rf(gatewayConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
