// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// ClientService is an autogenerated mock type for the ClientService type
type ClientService struct {
	mock.Mock
}

// Get provides a mock function with given fields: method, baseUrl, v
func (_m *ClientService) Get(method string, baseUrl string, v interface{}) (*http.Response, error) {
	ret := _m.Called(method, baseUrl, v)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, string, interface{}) *http.Response); ok {
		r0 = rf(method, baseUrl, v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, interface{}) error); ok {
		r1 = rf(method, baseUrl, v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
