// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import service "hidevops.io/mio/pkg/auth/service"

// OauthService is an autogenerated mock type for the OauthService type
type OauthService struct {
	mock.Mock
}

// GetAuthURL provides a mock function with given fields: a
func (_m *OauthService) GetAuthURL(a *service.Auth) string {
	ret := _m.Called(a)

	var r0 string
	if rf, ok := ret.Get(0).(func(*service.Auth) string); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
