language: go

go:
- "1.12.x"

git:
  depth: 1

branches:
  only:
  - master

go_import_path: hidevops.io/mio

install: true

env:
  - APP_PROFILES_ACTIVE=local KUBE_WATCH_TIMEOUT=1 GO111MODULE=on

script:
  - go test -v ./... -coverprofile=coverage.out -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

