apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: 2019-06-17T11:27:33Z
  name: default
  namespace: hidevopsio
  resourceVersion: "2892849"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/hidevopsio/roles/default
  uid: e6725256-90f2-11e9-84c8-005056ac7602
rules:
  - apiGroups:
      - cube.io
    resources:
      - builds
      - buildconfigs
      - deployments
      - deploymentconfigs
      - gatewayconfigs
      - imagestreams
      - pipelines
      - pipelineconfigs
      - serviceconfigs
      - sourceconfigs
      - tests
      - testconfigs
      - apps
    verbs:
      - get
      - list
      - watch
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
      - update
      - create