apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: 2019-06-17T11:27:33Z
  name: default
  namespace: hidevopsio
  resourceVersion: "2892850"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/hidevopsio/rolebindings/default
  uid: e675482a-90f2-11e9-84c8-005056ac7602
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hidevopsio