// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buildconfig.proto

package protobuf

/*
target package name
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// rpc command (CommandRequest) returns (CommandResponse) {}
// SourceCodePull
type SourceCodePullRequest struct {
	CloneType            string   `protobuf:"bytes,1,opt,name=cloneType,proto3" json:"cloneType,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Branch               string   `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	DstDir               string   `protobuf:"bytes,4,opt,name=dstDir,proto3" json:"dstDir,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Depth                int32    `protobuf:"varint,7,opt,name=depth,proto3" json:"depth,omitempty"`
	Namespace            string   `protobuf:"bytes,8,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Token                string   `protobuf:"bytes,10,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceCodePullRequest) Reset()         { *m = SourceCodePullRequest{} }
func (m *SourceCodePullRequest) String() string { return proto.CompactTextString(m) }
func (*SourceCodePullRequest) ProtoMessage()    {}
func (*SourceCodePullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{0}
}
func (m *SourceCodePullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceCodePullRequest.Unmarshal(m, b)
}
func (m *SourceCodePullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceCodePullRequest.Marshal(b, m, deterministic)
}
func (dst *SourceCodePullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceCodePullRequest.Merge(dst, src)
}
func (m *SourceCodePullRequest) XXX_Size() int {
	return xxx_messageInfo_SourceCodePullRequest.Size(m)
}
func (m *SourceCodePullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceCodePullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SourceCodePullRequest proto.InternalMessageInfo

func (m *SourceCodePullRequest) GetCloneType() string {
	if m != nil {
		return m.CloneType
	}
	return ""
}

func (m *SourceCodePullRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SourceCodePullRequest) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *SourceCodePullRequest) GetDstDir() string {
	if m != nil {
		return m.DstDir
	}
	return ""
}

func (m *SourceCodePullRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SourceCodePullRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SourceCodePullRequest) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *SourceCodePullRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SourceCodePullRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SourceCodePullRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SourceCodePullResponse struct {
	Code                 int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *SourceCodePullRequest `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SourceCodePullResponse) Reset()         { *m = SourceCodePullResponse{} }
func (m *SourceCodePullResponse) String() string { return proto.CompactTextString(m) }
func (*SourceCodePullResponse) ProtoMessage()    {}
func (*SourceCodePullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{1}
}
func (m *SourceCodePullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceCodePullResponse.Unmarshal(m, b)
}
func (m *SourceCodePullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceCodePullResponse.Marshal(b, m, deterministic)
}
func (dst *SourceCodePullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceCodePullResponse.Merge(dst, src)
}
func (m *SourceCodePullResponse) XXX_Size() int {
	return xxx_messageInfo_SourceCodePullResponse.Size(m)
}
func (m *SourceCodePullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceCodePullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SourceCodePullResponse proto.InternalMessageInfo

func (m *SourceCodePullResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SourceCodePullResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SourceCodePullResponse) GetData() *SourceCodePullRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

// Compile
type CompileRequest struct {
	CompileCmd           []*BuildCommand `protobuf:"bytes,1,rep,name=CompileCmd,proto3" json:"CompileCmd,omitempty"`
	Namespace            string          `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Context              string          `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CompileRequest) Reset()         { *m = CompileRequest{} }
func (m *CompileRequest) String() string { return proto.CompactTextString(m) }
func (*CompileRequest) ProtoMessage()    {}
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{2}
}
func (m *CompileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileRequest.Unmarshal(m, b)
}
func (m *CompileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileRequest.Marshal(b, m, deterministic)
}
func (dst *CompileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileRequest.Merge(dst, src)
}
func (m *CompileRequest) XXX_Size() int {
	return xxx_messageInfo_CompileRequest.Size(m)
}
func (m *CompileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompileRequest proto.InternalMessageInfo

func (m *CompileRequest) GetCompileCmd() []*BuildCommand {
	if m != nil {
		return m.CompileCmd
	}
	return nil
}

func (m *CompileRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CompileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompileRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type BuildCommand struct {
	CodeType             string   `protobuf:"bytes,1,opt,name=codeType,proto3" json:"codeType,omitempty"`
	ExecType             string   `protobuf:"bytes,2,opt,name=execType,proto3" json:"execType,omitempty"`
	Script               string   `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	CommandName          string   `protobuf:"bytes,4,opt,name=commandName,proto3" json:"commandName,omitempty"`
	Params               []string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildCommand) Reset()         { *m = BuildCommand{} }
func (m *BuildCommand) String() string { return proto.CompactTextString(m) }
func (*BuildCommand) ProtoMessage()    {}
func (*BuildCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{3}
}
func (m *BuildCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildCommand.Unmarshal(m, b)
}
func (m *BuildCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildCommand.Marshal(b, m, deterministic)
}
func (dst *BuildCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildCommand.Merge(dst, src)
}
func (m *BuildCommand) XXX_Size() int {
	return xxx_messageInfo_BuildCommand.Size(m)
}
func (m *BuildCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildCommand.DiscardUnknown(m)
}

var xxx_messageInfo_BuildCommand proto.InternalMessageInfo

func (m *BuildCommand) GetCodeType() string {
	if m != nil {
		return m.CodeType
	}
	return ""
}

func (m *BuildCommand) GetExecType() string {
	if m != nil {
		return m.ExecType
	}
	return ""
}

func (m *BuildCommand) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *BuildCommand) GetCommandName() string {
	if m != nil {
		return m.CommandName
	}
	return ""
}

func (m *BuildCommand) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type CompileResponse struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CompileRequest `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CompileResponse) Reset()         { *m = CompileResponse{} }
func (m *CompileResponse) String() string { return proto.CompactTextString(m) }
func (*CompileResponse) ProtoMessage()    {}
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{4}
}
func (m *CompileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileResponse.Unmarshal(m, b)
}
func (m *CompileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileResponse.Marshal(b, m, deterministic)
}
func (dst *CompileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileResponse.Merge(dst, src)
}
func (m *CompileResponse) XXX_Size() int {
	return xxx_messageInfo_CompileResponse.Size(m)
}
func (m *CompileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompileResponse proto.InternalMessageInfo

func (m *CompileResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CompileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CompileResponse) GetData() *CompileRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

// imageBuild
type ImageBuildRequest struct {
	App                  string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	S2IImage             string   `protobuf:"bytes,2,opt,name=s2iImage,proto3" json:"s2iImage,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	DockerFile           []string `protobuf:"bytes,4,rep,name=dockerFile,proto3" json:"dockerFile,omitempty"`
	Namespace            string   `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageBuildRequest) Reset()         { *m = ImageBuildRequest{} }
func (m *ImageBuildRequest) String() string { return proto.CompactTextString(m) }
func (*ImageBuildRequest) ProtoMessage()    {}
func (*ImageBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{5}
}
func (m *ImageBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageBuildRequest.Unmarshal(m, b)
}
func (m *ImageBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageBuildRequest.Marshal(b, m, deterministic)
}
func (dst *ImageBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageBuildRequest.Merge(dst, src)
}
func (m *ImageBuildRequest) XXX_Size() int {
	return xxx_messageInfo_ImageBuildRequest.Size(m)
}
func (m *ImageBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageBuildRequest proto.InternalMessageInfo

func (m *ImageBuildRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *ImageBuildRequest) GetS2IImage() string {
	if m != nil {
		return m.S2IImage
	}
	return ""
}

func (m *ImageBuildRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ImageBuildRequest) GetDockerFile() []string {
	if m != nil {
		return m.DockerFile
	}
	return nil
}

func (m *ImageBuildRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ImageBuildRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImageBuildRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ImageBuildRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ImageBuildResponse struct {
	Code                 int32              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ImageBuildRequest `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ImageBuildResponse) Reset()         { *m = ImageBuildResponse{} }
func (m *ImageBuildResponse) String() string { return proto.CompactTextString(m) }
func (*ImageBuildResponse) ProtoMessage()    {}
func (*ImageBuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{6}
}
func (m *ImageBuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageBuildResponse.Unmarshal(m, b)
}
func (m *ImageBuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageBuildResponse.Marshal(b, m, deterministic)
}
func (dst *ImageBuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageBuildResponse.Merge(dst, src)
}
func (m *ImageBuildResponse) XXX_Size() int {
	return xxx_messageInfo_ImageBuildResponse.Size(m)
}
func (m *ImageBuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageBuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImageBuildResponse proto.InternalMessageInfo

func (m *ImageBuildResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ImageBuildResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ImageBuildResponse) GetData() *ImageBuildRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

// imagePush
type ImagePushRequest struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	RegistryToken        string   `protobuf:"bytes,6,opt,name=registryToken,proto3" json:"registryToken,omitempty"`
	ImageName            string   `protobuf:"bytes,7,opt,name=imageName,proto3" json:"imageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImagePushRequest) Reset()         { *m = ImagePushRequest{} }
func (m *ImagePushRequest) String() string { return proto.CompactTextString(m) }
func (*ImagePushRequest) ProtoMessage()    {}
func (*ImagePushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{7}
}
func (m *ImagePushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImagePushRequest.Unmarshal(m, b)
}
func (m *ImagePushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImagePushRequest.Marshal(b, m, deterministic)
}
func (dst *ImagePushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImagePushRequest.Merge(dst, src)
}
func (m *ImagePushRequest) XXX_Size() int {
	return xxx_messageInfo_ImagePushRequest.Size(m)
}
func (m *ImagePushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImagePushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImagePushRequest proto.InternalMessageInfo

func (m *ImagePushRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ImagePushRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ImagePushRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImagePushRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ImagePushRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ImagePushRequest) GetRegistryToken() string {
	if m != nil {
		return m.RegistryToken
	}
	return ""
}

func (m *ImagePushRequest) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

type ImagePushResponse struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ImagePushRequest `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ImagePushResponse) Reset()         { *m = ImagePushResponse{} }
func (m *ImagePushResponse) String() string { return proto.CompactTextString(m) }
func (*ImagePushResponse) ProtoMessage()    {}
func (*ImagePushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{8}
}
func (m *ImagePushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImagePushResponse.Unmarshal(m, b)
}
func (m *ImagePushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImagePushResponse.Marshal(b, m, deterministic)
}
func (dst *ImagePushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImagePushResponse.Merge(dst, src)
}
func (m *ImagePushResponse) XXX_Size() int {
	return xxx_messageInfo_ImagePushResponse.Size(m)
}
func (m *ImagePushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImagePushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImagePushResponse proto.InternalMessageInfo

func (m *ImagePushResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ImagePushResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ImagePushResponse) GetData() *ImagePushRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

// test
type TestCommand struct {
	ExecType             string   `protobuf:"bytes,1,opt,name=execType,proto3" json:"execType,omitempty"`
	Script               string   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	CommandName          string   `protobuf:"bytes,3,opt,name=commandName,proto3" json:"commandName,omitempty"`
	Params               []string `protobuf:"bytes,4,rep,name=Params,proto3" json:"Params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCommand) Reset()         { *m = TestCommand{} }
func (m *TestCommand) String() string { return proto.CompactTextString(m) }
func (*TestCommand) ProtoMessage()    {}
func (*TestCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{9}
}
func (m *TestCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCommand.Unmarshal(m, b)
}
func (m *TestCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCommand.Marshal(b, m, deterministic)
}
func (dst *TestCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCommand.Merge(dst, src)
}
func (m *TestCommand) XXX_Size() int {
	return xxx_messageInfo_TestCommand.Size(m)
}
func (m *TestCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TestCommand proto.InternalMessageInfo

func (m *TestCommand) GetExecType() string {
	if m != nil {
		return m.ExecType
	}
	return ""
}

func (m *TestCommand) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *TestCommand) GetCommandName() string {
	if m != nil {
		return m.CommandName
	}
	return ""
}

func (m *TestCommand) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type TestsRequest struct {
	TestCmd              []*TestCommand `protobuf:"bytes,1,rep,name=TestCmd,proto3" json:"TestCmd,omitempty"`
	CodeType             string         `protobuf:"bytes,2,opt,name=codeType,proto3" json:"codeType,omitempty"`
	Namespace            string         `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TestsRequest) Reset()         { *m = TestsRequest{} }
func (m *TestsRequest) String() string { return proto.CompactTextString(m) }
func (*TestsRequest) ProtoMessage()    {}
func (*TestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{10}
}
func (m *TestsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestsRequest.Unmarshal(m, b)
}
func (m *TestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestsRequest.Marshal(b, m, deterministic)
}
func (dst *TestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestsRequest.Merge(dst, src)
}
func (m *TestsRequest) XXX_Size() int {
	return xxx_messageInfo_TestsRequest.Size(m)
}
func (m *TestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestsRequest proto.InternalMessageInfo

func (m *TestsRequest) GetTestCmd() []*TestCommand {
	if m != nil {
		return m.TestCmd
	}
	return nil
}

func (m *TestsRequest) GetCodeType() string {
	if m != nil {
		return m.CodeType
	}
	return ""
}

func (m *TestsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TestsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TestsResponse struct {
	Code                 int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *TestsRequest `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TestsResponse) Reset()         { *m = TestsResponse{} }
func (m *TestsResponse) String() string { return proto.CompactTextString(m) }
func (*TestsResponse) ProtoMessage()    {}
func (*TestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{11}
}
func (m *TestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestsResponse.Unmarshal(m, b)
}
func (m *TestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestsResponse.Marshal(b, m, deterministic)
}
func (dst *TestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestsResponse.Merge(dst, src)
}
func (m *TestsResponse) XXX_Size() int {
	return xxx_messageInfo_TestsResponse.Size(m)
}
func (m *TestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestsResponse proto.InternalMessageInfo

func (m *TestsResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TestsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TestsResponse) GetData() *TestsRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

// command
type Command struct {
	ExecType             string   `protobuf:"bytes,1,opt,name=execType,proto3" json:"execType,omitempty"`
	Script               string   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	CommandName          string   `protobuf:"bytes,3,opt,name=commandName,proto3" json:"commandName,omitempty"`
	Params               []string `protobuf:"bytes,4,rep,name=Params,proto3" json:"Params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{12}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetExecType() string {
	if m != nil {
		return m.ExecType
	}
	return ""
}

func (m *Command) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *Command) GetCommandName() string {
	if m != nil {
		return m.CommandName
	}
	return ""
}

func (m *Command) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type CommandRequest struct {
	CommandList          []*Command `protobuf:"bytes,1,rep,name=CommandList,proto3" json:"CommandList,omitempty"`
	CodeType             string     `protobuf:"bytes,2,opt,name=codeType,proto3" json:"codeType,omitempty"`
	Namespace            string     `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{13}
}
func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (dst *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(dst, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetCommandList() []*Command {
	if m != nil {
		return m.CommandList
	}
	return nil
}

func (m *CommandRequest) GetCodeType() string {
	if m != nil {
		return m.CodeType
	}
	return ""
}

func (m *CommandRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CommandResponse struct {
	Code                 int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *TestsRequest `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildconfig_c6b977a34843f145, []int{14}
}
func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (dst *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(dst, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommandResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CommandResponse) GetData() *TestsRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SourceCodePullRequest)(nil), "protobuf.SourceCodePullRequest")
	proto.RegisterType((*SourceCodePullResponse)(nil), "protobuf.SourceCodePullResponse")
	proto.RegisterType((*CompileRequest)(nil), "protobuf.CompileRequest")
	proto.RegisterType((*BuildCommand)(nil), "protobuf.BuildCommand")
	proto.RegisterType((*CompileResponse)(nil), "protobuf.CompileResponse")
	proto.RegisterType((*ImageBuildRequest)(nil), "protobuf.ImageBuildRequest")
	proto.RegisterType((*ImageBuildResponse)(nil), "protobuf.ImageBuildResponse")
	proto.RegisterType((*ImagePushRequest)(nil), "protobuf.ImagePushRequest")
	proto.RegisterType((*ImagePushResponse)(nil), "protobuf.ImagePushResponse")
	proto.RegisterType((*TestCommand)(nil), "protobuf.TestCommand")
	proto.RegisterType((*TestsRequest)(nil), "protobuf.TestsRequest")
	proto.RegisterType((*TestsResponse)(nil), "protobuf.TestsResponse")
	proto.RegisterType((*Command)(nil), "protobuf.Command")
	proto.RegisterType((*CommandRequest)(nil), "protobuf.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "protobuf.CommandResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuildConfigServiceClient is the client API for BuildConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuildConfigServiceClient interface {
	SourceCodePull(ctx context.Context, in *SourceCodePullRequest, opts ...grpc.CallOption) (*SourceCodePullResponse, error)
	Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error)
	ImageBuild(ctx context.Context, in *ImageBuildRequest, opts ...grpc.CallOption) (*ImageBuildResponse, error)
	ImagePush(ctx context.Context, in *ImagePushRequest, opts ...grpc.CallOption) (*ImagePushResponse, error)
	Test(ctx context.Context, in *TestsRequest, opts ...grpc.CallOption) (*TestsResponse, error)
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type buildConfigServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuildConfigServiceClient(cc *grpc.ClientConn) BuildConfigServiceClient {
	return &buildConfigServiceClient{cc}
}

func (c *buildConfigServiceClient) SourceCodePull(ctx context.Context, in *SourceCodePullRequest, opts ...grpc.CallOption) (*SourceCodePullResponse, error) {
	out := new(SourceCodePullResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BuildConfigService/SourceCodePull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildConfigServiceClient) Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error) {
	out := new(CompileResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BuildConfigService/Compile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildConfigServiceClient) ImageBuild(ctx context.Context, in *ImageBuildRequest, opts ...grpc.CallOption) (*ImageBuildResponse, error) {
	out := new(ImageBuildResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BuildConfigService/ImageBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildConfigServiceClient) ImagePush(ctx context.Context, in *ImagePushRequest, opts ...grpc.CallOption) (*ImagePushResponse, error) {
	out := new(ImagePushResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BuildConfigService/ImagePush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildConfigServiceClient) Test(ctx context.Context, in *TestsRequest, opts ...grpc.CallOption) (*TestsResponse, error) {
	out := new(TestsResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BuildConfigService/test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildConfigServiceClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BuildConfigService/command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildConfigServiceServer is the server API for BuildConfigService service.
type BuildConfigServiceServer interface {
	SourceCodePull(context.Context, *SourceCodePullRequest) (*SourceCodePullResponse, error)
	Compile(context.Context, *CompileRequest) (*CompileResponse, error)
	ImageBuild(context.Context, *ImageBuildRequest) (*ImageBuildResponse, error)
	ImagePush(context.Context, *ImagePushRequest) (*ImagePushResponse, error)
	Test(context.Context, *TestsRequest) (*TestsResponse, error)
	Command(context.Context, *CommandRequest) (*CommandResponse, error)
}

func RegisterBuildConfigServiceServer(s *grpc.Server, srv BuildConfigServiceServer) {
	s.RegisterService(&_BuildConfigService_serviceDesc, srv)
}

func _BuildConfigService_SourceCodePull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceCodePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildConfigServiceServer).SourceCodePull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BuildConfigService/SourceCodePull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildConfigServiceServer).SourceCodePull(ctx, req.(*SourceCodePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildConfigService_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildConfigServiceServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BuildConfigService/Compile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildConfigServiceServer).Compile(ctx, req.(*CompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildConfigService_ImageBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildConfigServiceServer).ImageBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BuildConfigService/ImageBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildConfigServiceServer).ImageBuild(ctx, req.(*ImageBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildConfigService_ImagePush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImagePushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildConfigServiceServer).ImagePush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BuildConfigService/ImagePush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildConfigServiceServer).ImagePush(ctx, req.(*ImagePushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildConfigService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildConfigServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BuildConfigService/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildConfigServiceServer).Test(ctx, req.(*TestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildConfigService_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildConfigServiceServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BuildConfigService/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildConfigServiceServer).Command(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BuildConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.BuildConfigService",
	HandlerType: (*BuildConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SourceCodePull",
			Handler:    _BuildConfigService_SourceCodePull_Handler,
		},
		{
			MethodName: "Compile",
			Handler:    _BuildConfigService_Compile_Handler,
		},
		{
			MethodName: "ImageBuild",
			Handler:    _BuildConfigService_ImageBuild_Handler,
		},
		{
			MethodName: "ImagePush",
			Handler:    _BuildConfigService_ImagePush_Handler,
		},
		{
			MethodName: "test",
			Handler:    _BuildConfigService_Test_Handler,
		},
		{
			MethodName: "command",
			Handler:    _BuildConfigService_Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buildconfig.proto",
}

func init() { proto.RegisterFile("buildconfig.proto", fileDescriptor_buildconfig_c6b977a34843f145) }

var fileDescriptor_buildconfig_c6b977a34843f145 = []byte{
	// 849 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x96, 0xdd, 0x6a, 0xdb, 0x30,
	0x14, 0xc7, 0xeb, 0x38, 0x9f, 0x27, 0x6d, 0x97, 0x8a, 0x35, 0xf3, 0xd2, 0xb2, 0x05, 0xb3, 0x8b,
	0x32, 0x46, 0x0a, 0x29, 0x14, 0x76, 0x37, 0x9a, 0x51, 0x28, 0x8c, 0x12, 0xd2, 0xee, 0x01, 0x1c,
	0x5b, 0x4d, 0x4d, 0x63, 0xcb, 0xb5, 0xec, 0x7e, 0xd0, 0x67, 0xe8, 0xd5, 0x76, 0xb1, 0x97, 0xd9,
	0x5b, 0xec, 0x7e, 0xaf, 0x32, 0xf4, 0x61, 0x5b, 0x4a, 0x93, 0x8c, 0x85, 0x8d, 0x5d, 0x45, 0xe7,
	0x1c, 0x59, 0x3a, 0xfa, 0xfd, 0x8f, 0x8e, 0x02, 0x5b, 0xe3, 0xd4, 0x9f, 0x7a, 0x2e, 0x09, 0x2f,
	0xfc, 0x49, 0x2f, 0x8a, 0x49, 0x42, 0x50, 0x9d, 0xff, 0x8c, 0xd3, 0x0b, 0xfb, 0xb1, 0x04, 0xdb,
	0x67, 0x24, 0x8d, 0x5d, 0x3c, 0x20, 0x1e, 0x1e, 0xa6, 0xd3, 0xe9, 0x08, 0x5f, 0xa7, 0x98, 0x26,
	0x68, 0x17, 0x1a, 0xee, 0x94, 0x84, 0xf8, 0xfc, 0x3e, 0xc2, 0x96, 0xd1, 0x35, 0xf6, 0x1a, 0xa3,
	0xc2, 0x81, 0x5a, 0x60, 0xa6, 0xf1, 0xd4, 0x2a, 0x71, 0x3f, 0x1b, 0xa2, 0x36, 0x54, 0xc7, 0xb1,
	0x13, 0xba, 0x97, 0x96, 0xc9, 0x9d, 0xd2, 0x62, 0x7e, 0x8f, 0x26, 0x1f, 0xfd, 0xd8, 0x2a, 0x0b,
	0xbf, 0xb0, 0x50, 0x07, 0xea, 0x29, 0xc5, 0x71, 0xe8, 0x04, 0xd8, 0xaa, 0xf0, 0x48, 0x6e, 0xb3,
	0x58, 0xe4, 0x50, 0x7a, 0x4b, 0x62, 0xcf, 0xaa, 0x8a, 0x58, 0x66, 0xa3, 0xe7, 0x50, 0xf1, 0x70,
	0x94, 0x5c, 0x5a, 0xb5, 0xae, 0xb1, 0x57, 0x19, 0x09, 0x83, 0x65, 0xcb, 0xbe, 0xa4, 0x91, 0xe3,
	0x62, 0xab, 0x2e, 0xb2, 0xcd, 0x1d, 0x08, 0x41, 0x99, 0xef, 0xd3, 0xe0, 0x01, 0x3e, 0x66, 0xeb,
	0x24, 0xe4, 0x0a, 0x87, 0x16, 0x70, 0xa7, 0x30, 0xec, 0x07, 0x68, 0xcf, 0xe2, 0xa0, 0x11, 0x09,
	0x29, 0x5f, 0xc3, 0x25, 0x9e, 0x40, 0x51, 0x19, 0xf1, 0x31, 0xb2, 0xa0, 0x16, 0x60, 0x4a, 0x9d,
	0x09, 0x96, 0x24, 0x32, 0x13, 0x1d, 0x40, 0xd9, 0x73, 0x12, 0x87, 0xb3, 0x68, 0xf6, 0x5f, 0xf7,
	0x32, 0xe0, 0xbd, 0xb9, 0xb0, 0x47, 0x7c, 0xb2, 0xfd, 0xd5, 0x80, 0xcd, 0x01, 0x09, 0x22, 0x7f,
	0x8a, 0x33, 0x15, 0x0e, 0x01, 0xa4, 0x67, 0x10, 0x78, 0x96, 0xd1, 0x35, 0xf7, 0x9a, 0xfd, 0x76,
	0xb1, 0xda, 0x11, 0x93, 0x76, 0x40, 0x82, 0xc0, 0x09, 0xbd, 0x91, 0x32, 0x53, 0xe7, 0x51, 0x5a,
	0xc4, 0xc3, 0x54, 0x78, 0x58, 0x50, 0x73, 0x49, 0x98, 0xe0, 0xbb, 0x44, 0x0a, 0x95, 0x99, 0xf6,
	0x37, 0x03, 0xd6, 0xd5, 0x8d, 0x98, 0x3c, 0xec, 0xf8, 0x4a, 0x65, 0xe4, 0x36, 0x8b, 0xe1, 0x3b,
	0xec, 0xf2, 0x98, 0xd8, 0x37, 0xb7, 0x59, 0x29, 0x50, 0x37, 0xf6, 0xa3, 0x24, 0x2b, 0x11, 0x61,
	0xa1, 0x2e, 0x34, 0x5d, 0xb1, 0xf4, 0x29, 0xcb, 0x4a, 0x6c, 0xaf, 0xba, 0xd8, 0x97, 0x91, 0x13,
	0x3b, 0x01, 0xb5, 0x2a, 0x5d, 0x93, 0x7d, 0x29, 0x2c, 0x3b, 0x80, 0x67, 0x39, 0xb0, 0x95, 0x74,
	0x7a, 0xa7, 0xe9, 0x64, 0x15, 0x64, 0x75, 0x1d, 0xa4, 0x40, 0x3f, 0x0d, 0xd8, 0x3a, 0x09, 0x9c,
	0x09, 0xe6, 0x38, 0x32, 0x8d, 0x5a, 0x60, 0x3a, 0x51, 0x24, 0x49, 0xb0, 0x21, 0x83, 0x40, 0xfb,
	0x3e, 0x9f, 0x99, 0x41, 0xc8, 0x6c, 0x96, 0x5f, 0xe2, 0x4c, 0xa8, 0x65, 0xf2, 0x83, 0xf0, 0x31,
	0x7a, 0x05, 0xe0, 0x11, 0xf7, 0x0a, 0xc7, 0xc7, 0xfe, 0x94, 0x9d, 0x9f, 0x45, 0x14, 0x8f, 0xae,
	0x66, 0x65, 0x91, 0x9a, 0x55, 0x45, 0x4d, 0xf5, 0x76, 0xd5, 0x96, 0xdc, 0xae, 0xba, 0x7e, 0xbb,
	0x6c, 0x0a, 0x48, 0x3d, 0xe0, 0x4a, 0x4c, 0xf7, 0x35, 0xa6, 0x3b, 0x05, 0xd3, 0x27, 0xe8, 0x24,
	0xd6, 0x1f, 0x06, 0xb4, 0x78, 0x6c, 0x98, 0xd2, 0xcb, 0x8c, 0x6a, 0xc6, 0xc9, 0x50, 0x38, 0xfd,
	0x79, 0x55, 0xab, 0x1c, 0xca, 0x4b, 0x38, 0x54, 0x66, 0xba, 0xcc, 0x1b, 0xd8, 0x88, 0xf1, 0xc4,
	0xa7, 0x49, 0x7c, 0x7f, 0xce, 0xbb, 0x84, 0x80, 0xab, 0x3b, 0x59, 0x3e, 0x3e, 0xcb, 0xfb, 0xb4,
	0xc0, 0x5c, 0x38, 0xec, 0x6b, 0x59, 0x2c, 0xe2, 0x54, 0x2b, 0xa1, 0xec, 0x69, 0x28, 0x3b, 0x33,
	0x28, 0x15, 0x5c, 0x92, 0xe4, 0x03, 0x34, 0xcf, 0x31, 0x4d, 0x94, 0x8b, 0x9a, 0x5f, 0x46, 0x63,
	0xe1, 0x65, 0x2c, 0x2d, 0xbb, 0x8c, 0xe6, 0xdc, 0xcb, 0x38, 0x14, 0x97, 0x51, 0x54, 0xaa, 0xb4,
	0xec, 0x47, 0x03, 0xd6, 0xd9, 0xee, 0x34, 0x93, 0x70, 0x1f, 0x6a, 0x3c, 0x9b, 0xbc, 0x73, 0x6d,
	0x17, 0x07, 0x50, 0xd2, 0x1c, 0x65, 0xb3, 0xb4, 0xc6, 0x52, 0x9a, 0x69, 0x2c, 0x9a, 0xf6, 0xe6,
	0x22, 0xed, 0xcb, 0x85, 0xf6, 0xb6, 0x0f, 0x1b, 0x32, 0x9d, 0x95, 0xd8, 0xbf, 0xd5, 0xd8, 0xb7,
	0xf5, 0xd4, 0xa9, 0xce, 0xfd, 0x16, 0x6a, 0xff, 0x87, 0xf9, 0x17, 0xf1, 0x64, 0x70, 0x8c, 0x92,
	0xfa, 0x01, 0x34, 0xa5, 0xe7, 0x93, 0x4f, 0x13, 0x49, 0x7e, 0x4b, 0xeb, 0x6c, 0x7c, 0xba, 0x3a,
	0xeb, 0x2f, 0x93, 0xbf, 0xe2, 0x6d, 0x59, 0x24, 0xf5, 0xaf, 0xd9, 0xf7, 0xbf, 0x9b, 0x80, 0xe4,
	0xf3, 0xc4, 0xfe, 0xe2, 0x9c, 0xe1, 0xf8, 0xc6, 0x77, 0x31, 0xfa, 0x0c, 0x9b, 0xfa, 0x5b, 0x8b,
	0x7e, 0xf7, 0x0a, 0x77, 0xba, 0x8b, 0x27, 0x88, 0x53, 0xd8, 0x6b, 0xe8, 0x03, 0x57, 0x9a, 0x3d,
	0x0d, 0x68, 0xe1, 0x6b, 0xd1, 0x79, 0x39, 0x27, 0x92, 0xaf, 0x70, 0x02, 0x50, 0x34, 0x42, 0xb4,
	0xac, 0x3d, 0x76, 0x76, 0xe7, 0x07, 0xf3, 0xa5, 0x8e, 0xa1, 0x91, 0x37, 0x02, 0xb4, 0xa4, 0x3b,
	0x74, 0x76, 0xe6, 0xc6, 0xf2, 0x75, 0xde, 0x43, 0x39, 0x61, 0xa5, 0xb3, 0x00, 0x74, 0xe7, 0xc5,
	0x13, 0xbf, 0xca, 0x43, 0xd6, 0xe9, 0x0c, 0x0f, 0xa5, 0x24, 0x67, 0x78, 0xa8, 0x75, 0x61, 0xaf,
	0x1d, 0x1d, 0x42, 0xd7, 0x27, 0x3d, 0x0f, 0xdf, 0x90, 0x88, 0xf6, 0xdc, 0x74, 0x8c, 0xf7, 0x9d,
	0x09, 0x0e, 0x93, 0x9e, 0xf2, 0xb7, 0xf5, 0xa8, 0xa5, 0x08, 0x3c, 0x64, 0x4b, 0x0d, 0x8d, 0x71,
	0x95, 0xaf, 0x79, 0xf0, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x94, 0x2e, 0x74, 0xe0, 0x0a, 0x00,
	0x00,
}
