apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.cube.io
spec:
  group: cube.io
  version: v1alpha1
  names:
    kind: App
    plural: apps
  scope: Namespaced