apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployments.cube.io
spec:
  group: cube.io
  version: v1alpha1
  names:
    kind: Deployment
    plural: deployments
  scope: Namespaced