apiVersion: cube.io/v1alpha1
kind: BuildConfig
metadata:
  name: node
  namespace: {{ .Values.namespace }}
spec:
  app: ""
  baseImage: {{ .Values.go.nodeImage }}
  cloneConfig:
    branch: ""
    dstDir: /opt/app-root/src
    password: ""
    url: ""
    username: ""
  cloneType: ""
  codeType: node
  compileCmd:
  - commandName: pwd
  - Script: GOOS=linux go build -o app
    execType: script
  - commandName: pwd
  - Script: ls
    execType: script
  deployData:
    envs:
      CODE_TYPE: node
      DOCKER_API_VERSION: "1.24"
    hostPathVolumes:
    - name: "docker"
      volumeSource: /var/lib/docker
      readOnly: true
      mountPath: /var/lib/docker
      subPath:
    - name: "docker-sock"
      volumeSource: /var/run/docker.sock
      readOnly: true
      mountPath: /var/run/docker.sock
      subPath:
    ports:
    - 8080
    - 7575
    replicas: 1
  dockerAuthConfig:
    password: {{ .Values.docker.password }}
    username: {{ .Values.docker.username }}
  dockerFile:
  - FROM clarechu/base-go:v1.0.0
  - COPY .  /root/
  - WORKDIR /root/svr
  - ENTRYPOINT ["npm", "start"]
  dockerRegistry: {{ .Values.docker.registy }}
  nodeService: ""
  tasks:
  - name: createService
  - name: deployNode
  - name: clone
  - name: compile
  - name: buildImage
  - name: pushImage
  - name: deleteDeployment
status:
  lastVersion: 1

