apiVersion: cube.io/v1alpha1
kind: GatewayConfig
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/rewrite-target: /
  name: node
  namespace: {{ .Values.namespace }}
spec:
  eventType: null
  hosts:
    - dev1.apps.cloud2go.cn
  httpIfTerminated: false
  httpsOnly: false
  kongAdminUrl:
  preserveHost: true
  profile:
  retries: "5"
  stripUri: true
  upstreamConnectTimeout: 60000
  upstreamReadTimeout: 60000
  upstreamSendTimeout: 60000
  upstreamUrl: ""
  uris: null
status:
  metadata: {}
