apiVersion: cube.io/v1alpha1
kind: PipelineConfig
metadata:
  name: node
  namespace: {{ .Values.namespace }}
spec:
  app: ""
  dockerRegistry: ""
  events:
  - eventTypes: build
    name: node
  - eventTypes: deploy
    name: node
  - eventTypes: service
    name: node
  - eventTypes: gateway
    name: node
  profile: dev
  version: v1
  branch: "master"
status: {}

