apiVersion: cube.io/v1alpha1
kind: ServiceConfig
metadata:
  labels:
    profile: dev
  name: node
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-8085
    port: 8085
    protocol: TCP
    targetPort: 8085
status:
  metadata: {}
