FROM hidevopsio/s2i-nodejs

RUN mkdir ${HOME}/ && chmod 755 ${HOME}

WORKDIR ${HOME}

COPY agent ${HOME}/agent

COPY config/ ${HOME}/config/

ENV npm_config_registry ${npm_config_registry}
ENV npm_config_disturl https://npm.taobao.org/dist/
ENV npm_config_phantomjs_cdnurl https://npm.taobao.org/dist/phantomjs/
ENV npm_config_phantomjs_cdnurl https://npm.taobao.org/dist/phantomjs/
ENV npm_config_electron_mirror https://npm.taobao.org/mirrors/electron/
ENV npm_config_sass_binary_site https://npm.taobao.org/mirrors/node-sass/

EXPOSE 7575
EXPOSE 8080

CMD ["./agent"]