FROM ${HOST}/hidevopsio/s2i-java

RUN mkdir ${HOME}/ && chmod 755 ${HOME}

WORKDIR ${HOME}/

COPY agent ${HOME}/agent

COPY config/ ${HOME}/config/

ENV MAVEN_MIRROR_URL
ENV MAVEN_CLEAR_REPO false

EXPOSE 7575
EXPOSE 8080

CMD ["./agent"]