FROM hidevopsio/centos7:1.0
WORKDIR  ${HOME}/
COPY config ${HOME}/config
COPY agent ${HOME}/agent
RUN  chmod +x ${HOME}/agent
ENV DOCKER_API_VERSION 1.24

EXPOSE 7575
EXPOSE 8080

USER 0

CMD ["./agent"]
