// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import v1 "k8s.io/api/core/v1"

// ConfigMapsAggregate is an autogenerated mock type for the ConfigMapsAggregate type
type ConfigMapsAggregate struct {
	mock.Mock
}

// Create provides a mock function with given fields: name, namespace, data
func (_m *ConfigMapsAggregate) Create(name string, namespace string, data map[string]string) (*v1.ConfigMap, error) {
	ret := _m.Called(name, namespace, data)

	var r0 *v1.ConfigMap
	if rf, ok := ret.Get(0).(func(string, string, map[string]string) *v1.ConfigMap); ok {
		r0 = rf(name, namespace, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigMap)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, map[string]string) error); ok {
		r1 = rf(name, namespace, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: name, namespace
func (_m *ConfigMapsAggregate) Get(name string, namespace string) (*v1.ConfigMap, error) {
	ret := _m.Called(name, namespace)

	var r0 *v1.ConfigMap
	if rf, ok := ret.Get(0).(func(string, string) *v1.ConfigMap); ok {
		r0 = rf(name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigMap)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
