// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import v1alpha1 "hidevops.io/cube/pkg/apis/cube/v1alpha1"

// GatewayAggregate is an autogenerated mock type for the GatewayAggregate type
type GatewayAggregate struct {
	mock.Mock
}

// Create provides a mock function with given fields: gateway
func (_m *GatewayAggregate) Create(gateway *v1alpha1.GatewayConfig) error {
	ret := _m.Called(gateway)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.GatewayConfig) error); ok {
		r0 = rf(gateway)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
