// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import command "hidevops.io/cube/manager/pkg/command"
import mock "github.com/stretchr/testify/mock"
import v1alpha1 "hidevops.io/cube/pkg/apis/cube/v1alpha1"

// GatewayConfigAggregate is an autogenerated mock type for the GatewayConfigAggregate type
type GatewayConfigAggregate struct {
	mock.Mock
}

// Create provides a mock function with given fields: params
func (_m *GatewayConfigAggregate) Create(params *command.PipelineReqParams) (*v1alpha1.GatewayConfig, error) {
	ret := _m.Called(params)

	var r0 *v1alpha1.GatewayConfig
	if rf, ok := ret.Get(0).(func(*command.PipelineReqParams) *v1alpha1.GatewayConfig); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.GatewayConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*command.PipelineReqParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Template provides a mock function with given fields: cmd
func (_m *GatewayConfigAggregate) Template(cmd *command.GatewayConfig) (*v1alpha1.GatewayConfig, error) {
	ret := _m.Called(cmd)

	var r0 *v1alpha1.GatewayConfig
	if rf, ok := ret.Get(0).(func(*command.GatewayConfig) *v1alpha1.GatewayConfig); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.GatewayConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*command.GatewayConfig) error); ok {
		r1 = rf(cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
