// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NamespaceAggregate is an autogenerated mock type for the NamespaceAggregate type
type NamespaceAggregate struct {
	mock.Mock
}

// Create provides a mock function with given fields: namespace
func (_m *NamespaceAggregate) Create(namespace string) error {
	ret := _m.Called(namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HarborCreate provides a mock function with given fields: namespace
func (_m *NamespaceAggregate) HarborCreate(namespace string) error {
	ret := _m.Called(namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitNamespace provides a mock function with given fields: namespace
func (_m *NamespaceAggregate) InitNamespace(namespace string) error {
	ret := _m.Called(namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
