// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import command "hidevops.io/cube/manager/pkg/command"
import mock "github.com/stretchr/testify/mock"
import v1alpha1 "hidevops.io/cube/pkg/apis/cube/v1alpha1"

// ServiceConfigAggregate is an autogenerated mock type for the ServiceConfigAggregate type
type ServiceConfigAggregate struct {
	mock.Mock
}

// Create provides a mock function with given fields: params
func (_m *ServiceConfigAggregate) Create(params *command.PipelineReqParams) (*v1alpha1.ServiceConfig, error) {
	ret := _m.Called(params)

	var r0 *v1alpha1.ServiceConfig
	if rf, ok := ret.Get(0).(func(*command.PipelineReqParams) *v1alpha1.ServiceConfig); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ServiceConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*command.PipelineReqParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteService provides a mock function with given fields: name, namespace
func (_m *ServiceConfigAggregate) DeleteService(name string, namespace string) error {
	ret := _m.Called(name, namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Template provides a mock function with given fields: cmd
func (_m *ServiceConfigAggregate) Template(cmd *command.ServiceConfig) (*v1alpha1.ServiceConfig, error) {
	ret := _m.Called(cmd)

	var r0 *v1alpha1.ServiceConfig
	if rf, ok := ret.Get(0).(func(*command.ServiceConfig) *v1alpha1.ServiceConfig); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ServiceConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*command.ServiceConfig) error); ok {
		r1 = rf(cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
