/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	cube_v1alpha1 "hidevops.io/cube/pkg/apis/cube/v1alpha1"
	versioned "hidevops.io/cube/pkg/client/clientset/versioned"
	internalinterfaces "hidevops.io/cube/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "hidevops.io/cube/pkg/client/listers/cube/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TestConfigInformer provides access to a shared informer and lister for
// TestConfigs.
type TestConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TestConfigLister
}

type testConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTestConfigInformer constructs a new informer for TestConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTestConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTestConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTestConfigInformer constructs a new informer for TestConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTestConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CubeV1alpha1().TestConfigs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CubeV1alpha1().TestConfigs(namespace).Watch(options)
			},
		},
		&cube_v1alpha1.TestConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *testConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTestConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *testConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cube_v1alpha1.TestConfig{}, f.defaultInformer)
}

func (f *testConfigInformer) Lister() v1alpha1.TestConfigLister {
	return v1alpha1.NewTestConfigLister(f.Informer().GetIndexer())
}
