apiVersion: cube.io/v1alpha1
kind: PipelineConfig
metadata:
  name: go-mod
  namespace: hidevopsio
spec:
  app: ""
  dockerRegistry: ""
  events:
  - eventTypes: build
    name: go-mod
  - eventTypes: deploy
    name: go
  - eventTypes: service
    name: go
  - eventTypes: gateway
    name: go
  profile: dev
  version: v1
  branch: "master"
status: {}

