// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import command "hidevops.io/cube/console/pkg/command"
import mock "github.com/stretchr/testify/mock"

// CubeUpdateAggregate is an autogenerated mock type for the CubeUpdateAggregate type
type CubeUpdateAggregate struct {
	mock.Mock
}

// Add provides a mock function with given fields: name, update
func (_m *CubeUpdateAggregate) Add(name string, update *command.CubeUpdate) error {
	ret := _m.Called(name, update)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *command.CubeUpdate) error); ok {
		r0 = rf(name, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: name
func (_m *CubeUpdateAggregate) Delete(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: name
func (_m *CubeUpdateAggregate) Get(name string) (*command.CubeUpdate, error) {
	ret := _m.Called(name)

	var r0 *command.CubeUpdate
	if rf, ok := ret.Get(0).(func(string) *command.CubeUpdate); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.CubeUpdate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
