package constant

const (
	PipelineKind       = "Pipeline"
	PipelineApiVersion = "Pipeline.cube.io/v1alpha1"
	Name               = "name"
	Number             = "number"
	BuildConfigName    = "cube.io/buildConfig.name"
	Version            = "version"
	App                = "app"
	Success            = "success"
	Fail               = "fail"
	Running            = "running"
	Pending            = "pending"
	BuildPipeline      = "build"
	Deploy             = "deploy"
	Created            = "created"
	Service            = "service"
	Gateway            = "gateway"
	PipelineConfigName = "pipelineConfigName"
	CodeType           = "codeType"
	BuildVersion       = "buildVersion"
	Namespace          = "namespace"
	AppVersion         = "APP_VERSION"
	AppName            = "APP_NAME"
)
